print ("CS151 Lab 0")
print ("Zain")
print ("Zain likes to collect sneakers.")
print ("Zain is from Howard County Maryland.")
print ("Zain is a great hockey player.")
print ("Zain was born in Virginia.")
print ("Zain likes to travel to new places.")
