print ("CS151 Lab 0")
print ("Zain")
print ("Zain likes to collect sneakers.")
print ("Zain is from Howard County Maryland.")
print ("Zain is a great hockey player.")
print ("Zain was born in Virginia.")
print ("Zain likes to travel to new places.")
print ("CS151 Lab 0")
print ("Ethan")
print ("Ethan used to play pre-academy soccer.")
print ("Ethan enjoys karaoke.")
print ("Ethan invest in the stock market.")
print ("Ethan plays table tennis every day for 1 hour.")
print ("Ethan has been to New Zealand.")
